version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.single
    ports:
      - "8080:80"
      - "5432:5432"
    env_file:
      - /Users/arthur/roilux/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 